language: python
python:
- '3.3'
- '3.4'
- '3.5'
- "3.5-dev" # 3.5 development branch
#- "nightly" # currently points to 3.6-dev
bundler_args: "--retry 3"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose
script:
- nosetests --with-coverage --cover-package=BAC0 -v
after_success: coveralls
